# Generated by Django 3.1.5 on 2021-02-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Correo', models.EmailField(max_length=254, unique=True, verbose_name='correo address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('FechaCreaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido1', models.CharField(max_length=100)),
                ('Apellido2', models.CharField(max_length=100)),
                ('Imagenperfil', models.TextField(max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('ComentariosId', models.AutoField(primary_key=True, serialize=False)),
                ('ComentariosContenido', models.TextField()),
                ('ComentariosFechaComentario', models.DateField(default=django.utils.timezone.now)),
                ('ComentariosEstado', models.BooleanField()),
                ('ComentariosUsuarioId', models.IntegerField()),
                ('ComentariosPostId', models.IntegerField()),
                ('ComentariosValoracioncomentariosId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenescomentarios',
            fields=[
                ('ImagenescomentariosId', models.AutoField(primary_key=True, serialize=False)),
                ('ImagenescomentariosNombre', models.CharField(max_length=255)),
                ('ImagenescomentariosTipo', models.CharField(max_length=50)),
                ('ImagenescomentariosArchivo', models.CharField(max_length=255)),
                ('ImagenescomentariosComentariosId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenespost',
            fields=[
                ('ImagenespostId', models.AutoField(primary_key=True, serialize=False)),
                ('ImagenespostNombre', models.CharField(max_length=255)),
                ('ImagenespostTipo', models.CharField(max_length=50)),
                ('ImagenespostArchivo', models.CharField(max_length=255)),
                ('ImagenespostPostId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('TipousuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('TipousuarioNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracioncomentarios',
            fields=[
                ('ValoraciValoracioncomentariosIdonId', models.AutoField(primary_key=True, serialize=False)),
                ('ValoracioncomentariosNumero', models.SmallIntegerField()),
                ('ValoracioncomentariosUsuarioId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracionpost',
            fields=[
                ('ValoracionpostId', models.AutoField(primary_key=True, serialize=False)),
                ('ValoracionpostNumero', models.SmallIntegerField()),
                ('ValoracionpostUsuarioId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('PostTitulo', models.CharField(max_length=255)),
                ('PostContenido', models.TextField()),
                ('PostFechaPublicacion', models.DateField(default=django.utils.timezone.now)),
                ('PostEstado', models.BooleanField()),
                ('PostUsuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PostValoracionpostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stackovergameApp.valoracionpost')),
            ],
        ),
    ]
