# Generated by Django 3.1.5 on 2021-01-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('ComentariosId', models.AutoField(primary_key=True, serialize=False)),
                ('ComentariosContenido', models.TextField()),
                ('ComentariosFechaComentario', models.DateField()),
                ('ComentariosEstado', models.BooleanField()),
                ('ComentariosUsuarioId', models.IntegerField()),
                ('ComentariosPostId', models.IntegerField()),
                ('ComentariosValoracioncomentariosId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenescomentarios',
            fields=[
                ('ImagenescomentariosId', models.AutoField(primary_key=True, serialize=False)),
                ('ImagenescomentariosNombre', models.CharField(max_length=255)),
                ('ImagenescomentariosTipo', models.CharField(max_length=50)),
                ('ImagenescomentariosArchivo', models.FileField(blank=True, null=True, upload_to='media/comentarios_picture')),
                ('ImagenescomentariosComentariosId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenespost',
            fields=[
                ('ImagenespostId', models.AutoField(primary_key=True, serialize=False)),
                ('ImagenespostNombre', models.CharField(max_length=255)),
                ('ImagenespostTipo', models.CharField(max_length=50)),
                ('ImagenespostArchivo', models.FileField(blank=True, null=True, upload_to='media/post_picture')),
                ('ImagenespostPostId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('PostTitulo', models.CharField(max_length=255)),
                ('PostContenido', models.TextField()),
                ('PostFechaPublicacion', models.DateField()),
                ('PostEstado', models.BooleanField()),
                ('PostUsuarioId', models.IntegerField()),
                ('PostValoracionpostId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('TipousuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('TipousuarioNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('UsuarioDni', models.CharField(max_length=9)),
                ('UsuarioNombre', models.CharField(max_length=50)),
                ('UsuarioApellido1', models.CharField(max_length=50)),
                ('UsuarioApellido2', models.CharField(max_length=50)),
                ('UsuarioLogin', models.CharField(max_length=50)),
                ('UsuarioPassword', models.CharField(max_length=512)),
                ('UsuarioEmail', models.CharField(max_length=255)),
                ('UsuarioToken', models.CharField(max_length=512)),
                ('UsuarioValidado', models.BooleanField()),
                ('UsuarioActivo', models.BooleanField()),
                ('UsuarioFechaCreacion', models.DateField()),
                ('UsuarioProfilePicture', models.FileField(blank=True, null=True, upload_to='media/profile_picture')),
                ('UsuarioTipousuarioId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracioncomentarios',
            fields=[
                ('ValoracionId', models.AutoField(primary_key=True, serialize=False)),
                ('ValoracionNumero', models.SmallIntegerField()),
                ('ValoracioncomentariosUsuarioId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracionpost',
            fields=[
                ('ValoracionId', models.AutoField(primary_key=True, serialize=False)),
                ('ValoracionNumero', models.SmallIntegerField()),
                ('ValoracionpostUsuarioId', models.IntegerField()),
            ],
        ),
    ]
