# Generated by Django 3.1.5 on 2021-06-06 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stackovergameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('GuideId', models.AutoField(primary_key=True, serialize=False)),
                ('GuideTitulo', models.CharField(max_length=255)),
                ('GuideContenido', models.TextField()),
                ('GuideFechaPublicacion', models.DateField(default=django.utils.timezone.now)),
                ('GuideEstado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsId', models.AutoField(primary_key=True, serialize=False)),
                ('NewsTitulo', models.CharField(max_length=255)),
                ('NewsContenido', models.TextField()),
                ('NewsFechaPublicacion', models.DateField(default=django.utils.timezone.now)),
                ('NewsEstado', models.BooleanField(default=True)),
            ],
        ),
    ]
